### ISSUE TITLE
how to implement Bootstrap on Rails 

### ISSUE THREAD

**Issue by htateno** [pndnism/Motiva#30]
## 🚸背景・目的

bootstrap をrailsに入れ込む方法を調べる

**Comment by pndnism** [comment]
ぽんちゃんが作ったhtmlをベースに、rails上で１画面実装してみる

**Comment by pndnism** [comment]
```html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
```

bootstrap反映するのは、ぽんちゃんが入れてた、↑のやついれるだけでOKそう？

**Comment by pndnism** [comment]
![image](https://user-images.githubusercontent.com/59597880/103233892-99826300-4981-11eb-9f2a-e2020a10a230.png)
こんな感じで、モデル経由でDBのデータを反映するように設定できた。
