### ISSUE TITLE
ER図の作成

### ISSUE THREAD

**Issue by momokok27** [pndnism/Motiva#43]
## 🚸背景・目的

データの構造をわかりやすくする

## 💬どのようなタスクか

1. ER図を作るためのツールを調べる
2. ER図作る

**Comment by momokok27** [comment]
![Motiva_ER_210117](https://user-images.githubusercontent.com/70589128/104843048-013a2700-590c-11eb-98f0-c095a1dd682a.jpg)
現状こんな感じです

**Comment by pndnism** [comment]
@o1hashimoto @htateno 
ER図とは↓
- https://products.sint.co.jp/ober/blog/create-er-diagram
- https://it-koala.com/entity-relationship-diagram-1897
- https://wa3.i-3-i.info/word11593.html

**Comment by pndnism** [comment]
- 見た目的なところで言うと、usersを中心に置くと、見やすくなるかも？
- Foreign Key（外部キー）を追記してもらえると良いかも（例えばhabit_listsテーブルはuser_idが外部キーになっているので、user_idの横にFKとか書いとくと）
- habit_listsのテーブル名って、habitsにするとか言う話やったっけ（habit_recordsの外部キーがhabit_idになっているのに対して、habit_listsの主キーがhabit_list_idになるのが気持ち悪い気がして）
- 年末に相談した話の備忘で書くと、将来的に現状のcolorsテーブルはcategoryテーブルにして、colorsテーブルは色の情報だけ持つか、もはや削除するかしたい

**Comment by momokok27** [comment]
- 見た目的なところで言うと、usersを中心に置くと、見やすくなるかも？
- Foreign Key（外部キー）を追記してもらえると良いかも（例えばhabit_listsテーブルはuser_idが外部キーになっているので、user_idの横にFKとか書いとくと）
　→了解！

- habit_listsのテーブル名って、habitsにするとか言う話やったっけ（habit_recordsの外部キーがhabit_idになっているのに対して、habit_listsの主キーがhabit_list_idになるのが気持ち悪い気がして）
　→Modelの定義で外部キーをhabit_idって指定する方法でやろうと話をしていたけど、やっぱり直したほうがいいかもしれんね〜やるわ！

- 年末に相談した話の備忘で書くと、将来的に現状のcolorsテーブルはcategoryテーブルにして、colorsテーブルは色の情報だけ持つか、もはや削除するかしたい
　→忘れてた！categoryにします。colorsはまあいらないかもね。

**Comment by htateno** [comment]
質問！deadlineとかを一つ一つのtodoに紐づけるのはmodelが担当する領域ですか！？？

**Comment by pndnism** [comment]
> 質問！deadlineとかを一つ一つのtodoに紐づけるのはmodelが担当する領域ですか！？？

データとして管理するのがmodelの領域、それをどの部分でどう入力させるか、がviewの担当範囲です！

**Comment by pndnism** [comment]
@momokok27 
draw.ioとかこのER図の作ってる場所のリンクを共有してもらっても良いかな

**Comment by momokok27** [comment]
@pndnism 今はローカル上で作ってて、github上に載せられるみたいなんだけど、そういうってどこのディレクトリにあげるのがいいかな？githubに載せないほうがいい？

**Comment by momokok27** [comment]
了解〜直接githubでディレクトリ作っていいかな？この方法で↓
https://qiita.com/tommy_aka_jps/items/b2ae85cbeab77e12a925

draw.ioで作ったよ！ここにはアップロードできなかった、、

**Comment by pndnism** [comment]
↑の方法で良いよ

やりたいこととしては、俺初めみんな編集できる状態にしたい。
draw.ioってwebアプリよね？作った時の共有URLとかなかったっけ
わからなそうならER図の方は一旦亀で進めてもらって大丈夫かと〜（それかどっか時間とって一緒にやりましょう〜）

**Comment by htateno** [comment]
重要そうだから時間あれば次のmtで話そうぜ

**Comment by pndnism** [comment]
ER図良さそう
クローズする
