### ISSUE TITLE
ユーザー登録ページでユーザーが登録された時にDBにデータが保存されるようにする

### ISSUE THREAD

**Issue by pndnism** [pndnism/Motiva#77]
## 💬どのようなタスクか

- ぽんちゃんの作ったhtmlをhtml.erbファイルに書き換える（載せ替える）
- html.erbの中身でデータ関連の部分をrubyコードで置き換える
    -> ユーザー登録に応じてデータがDBに投げられるようにする
- DBに入ったことを確認 

## 💡Output

- makeをしてMotivaのアプリを立ち上げて、ユーザー登録ページにおいて登録行動をしたら、DBに該当のデータが入っている状態になっている

**Comment by momokok27** [comment]
user新規登録時にDBにデータを入れることはできるようになった。

残タスク：パスワードのセキュリティを担保（ハッシュ化する）

**Comment by momokok27** [comment]
ハッシュ化も完了した。
